---
driver:
  name: vagrant
  synced_folders:
    - ['./', "/vagrant"]

provisioner:
  name: salt_solo
  formula: salt
  state_top:
     base:
      '*':
        - salt.webmonbot

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
    attributes:

verifier:
  name: shell
  command: py.test --host="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}" --junit-xml "junit-${KITCHEN_INSTANCE}.xml" "tests/integration/${KITCHEN_SUITE}"